### ISSUE TITLE
EM metric

### ISSUE THREAD

**Issue by davidmrau** [Hannibal046/xRAG#4]
Thanks for the great work. From your paper, I understood that you are using EM for the evaluation of the open QA datasets. From the evaluation code, it seems like you are using the Match metric. Could you please clarify?

https://github.com/Hannibal046/xRAG/blob/9858cb47137d49b2ce0714ee5c1222b0b3741e30/src/eval/run_eval.py#L127

**Comment by Hannibal046** [comment]
Hi, thanks for your interest in our work and sorry for the confusion. Since instruction-tuned LLM would inevitably generate verbose output, evaluation for openqa with exact match is very hard. So following most current papers, we adopt substring match. We would make it clear in the next version of our paper. 

Thanks for pointing this out!

**Comment by davidmrau** [comment]
Thanks for the fast response!
